import { NewsEvent } from '../types';

export const newsData: NewsEvent[] = [
  {
    id: 'news-1',
    title: 'Federal Reserve Maintains Interest Rates Amid Economic Uncertainty',
    date: '2025-01-29',
    source: 'Federal Reserve',
    sector: 'Economics',
    impact: 42.3,
    confidence: 0.94,
    summary: 'The Federal Reserve held interest rates steady at 5.25%-5.50%, citing the need to monitor inflation trends before considering rate cuts. Markets reacted positively to the decision.',
    verified: true,
    relatedIndices: ['S&P 500', 'NASDAQ', 'Treasury Yields'],
  },
  {
    id: 'news-2',
    title: 'New Administration Unveils Comprehensive AI Regulation Plan',
    date: '2025-01-28',
    source: 'White House',
    sector: 'Politics',
    impact: -35.7,
    confidence: 0.81,
    summary: 'Executive order introduces strict oversight for AI development, data privacy requirements, and liability frameworks. Tech sector faces increased compliance costs.',
    verified: true,
    relatedIndices: ['NASDAQ', 'Tech ETFs'],
  },
  {
    id: 'news-3',
    title: 'US-China Trade Dialogue Resumes With Optimistic Tone',
    date: '2025-01-25',
    source: 'USTR',
    sector: 'Global Trade',
    impact: 45.2,
    confidence: 0.77,
    summary: 'High-level trade officials from both nations met in Geneva, discussing tariff reductions and intellectual property protections. Market sentiment improved on hopes for de-escalation.',
    verified: true,
    relatedIndices: ['S&P 500', 'Emerging Markets', 'Materials'],
  },
  {
    id: 'news-4',
    title: 'December Jobs Report Exceeds Expectations',
    date: '2025-01-24',
    source: 'Bureau of Labor Statistics',
    sector: 'Economics',
    impact: 38.9,
    confidence: 0.91,
    summary: 'Non-farm payrolls added 256,000 jobs in December, well above the 165,000 forecast. Unemployment remains at 3.7%, indicating continued labor market strength.',
    verified: true,
    relatedIndices: ['S&P 500', 'Small Cap'],
  },
  {
    id: 'news-5',
    title: 'European Union Launches Carbon Border Adjustment Mechanism',
    date: '2025-01-18',
    source: 'European Commission',
    sector: 'Global Trade',
    impact: -28.4,
    confidence: 0.86,
    summary: 'EU implements CBAM on imports of steel, cement, and aluminum, requiring carbon certificates. US exporters face new compliance requirements and potential cost increases.',
    verified: true,
    relatedIndices: ['Materials', 'Energy', 'Industrials'],
  },
  {
    id: 'news-6',
    title: 'Senate Advances Bipartisan Infrastructure Investment Package',
    date: '2025-01-20',
    source: 'US Senate',
    sector: 'Politics',
    impact: 43.1,
    confidence: 0.83,
    summary: '$200 billion infrastructure bill passes key committee vote with strong bipartisan support. Focus on transportation, broadband, and renewable energy infrastructure.',
    verified: true,
    relatedIndices: ['Industrials', 'Materials', 'Utilities'],
  },
  {
    id: 'news-7',
    title: 'CPI Data Shows Inflation Holding Above Target',
    date: '2025-01-15',
    source: 'Bureau of Labor Statistics',
    sector: 'Economics',
    impact: 31.6,
    confidence: 0.89,
    summary: 'Consumer Price Index increased 2.9% year-over-year in December, remaining stubbornly above the Fed\'s 2% target. Core CPI rose 3.2%, driven by services inflation.',
    verified: true,
    relatedIndices: ['Treasury Yields', 'DXY', 'Gold'],
  },
  {
    id: 'news-8',
    title: 'Middle East Tensions Escalate, Oil Prices Surge',
    date: '2025-01-12',
    source: 'Reuters',
    sector: 'Global Trade',
    impact: -41.2,
    confidence: 0.79,
    summary: 'Geopolitical instability in key oil-producing regions drives crude prices up 8% in a single session. Supply chain concerns for global energy markets intensify.',
    verified: true,
    relatedIndices: ['Energy', 'S&P 500', 'WTI Crude'],
  },
  {
    id: 'news-9',
    title: 'Supreme Court Ruling Impacts Tech Sector Liability',
    date: '2025-01-10',
    source: 'US Supreme Court',
    sector: 'Politics',
    impact: -37.8,
    confidence: 0.88,
    summary: 'Landmark decision modifies Section 230 protections for online platforms, increasing liability for user-generated content. Tech companies face potential legal exposure.',
    verified: true,
    relatedIndices: ['NASDAQ', 'Communication Services'],
  },
  {
    id: 'news-10',
    title: 'Manufacturing PMI Signals Economic Expansion',
    date: '2025-01-08',
    source: 'ISM',
    sector: 'Economics',
    impact: 36.5,
    confidence: 0.85,
    summary: 'Institute for Supply Management reports manufacturing PMI of 52.3 for December, indicating expansion. New orders and production indices both increased.',
    verified: true,
    relatedIndices: ['Industrials', 'S&P 500'],
  },
  {
    id: 'news-11',
    title: 'ASEAN Nations Finalize Regional Trade Agreement',
    date: '2025-01-05',
    source: 'ASEAN Secretariat',
    sector: 'Global Trade',
    impact: 29.7,
    confidence: 0.74,
    summary: 'Ten Southeast Asian nations sign comprehensive economic partnership, reducing tariffs and harmonizing trade rules. Creates world\'s third-largest trade bloc.',
    verified: true,
    relatedIndices: ['Emerging Markets', 'Asia Pacific ETFs'],
  },
  {
    id: 'news-12',
    title: 'Congressional Committee Approves Tax Reform Proposal',
    date: '2025-01-03',
    source: 'House Ways and Means',
    sector: 'Politics',
    impact: 40.2,
    confidence: 0.80,
    summary: 'Proposed changes to corporate tax rates and R&D credits advance to full House vote. Analysts project significant impact on technology and pharmaceutical sectors.',
    verified: true,
    relatedIndices: ['S&P 500', 'Technology', 'Healthcare'],
  },
];
